document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\' type=\'text/css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'theme.css\' type=\'text/css\'>");
document.writeln("</head>");
document.writeln("<BODY>");
document.writeln("  <nav class=\'navbar navbar-expand-md bg-secondary navbar-dark\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <a class=\'navbar-brand\' href=\'#\'><img src=\"logo.png\"></a>");
document.writeln("      <button class=\'navbar-toggler navbar-toggler-right\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarSupportedContent\' aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'> <span class=\'navbar-toggler-icon\'></span> </button>");
document.writeln("      <div class=\'collapse navbar-collapse\' id=\'navbarSupportedContent\'>");
document.writeln("        <ul class=\'navbar-nav mr-auto\'>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link \' href=\'index.html\'>主页</a>    ");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link \' href=\'#\'>Pricing</a>");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link \' href=\'#\'>About</a>");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link \' href=\'#\'>Contact us</a>");
document.writeln("          </li>");
document.writeln("        </ul>");
document.writeln("        <form class=\'form-inline m-0 \'>");
document.writeln("          <input class=\'form-control mr-2\' type=\'text\' placeholder=\'Search\'>");
document.writeln("          <button class=\'btn btn-primary\' type=\'submit\'>Search</button>");
document.writeln("        </form>");
document.writeln("      </div>");
document.writeln("      <div class=\'row\'>");
document.writeln("        <div class=\'col-md-6\'></div>");
document.writeln("        <div class=\'col-2 order-lg-2 navbar-right\'>");
document.writeln("            <ul class=\'nav nav-pills\'>");
document.writeln("                <li>");
document.writeln("                    <i class=\'d-block fa fa-user-circle-o fa-2x \'  href=\'1.html\'> </i>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("			            <li><a  href=\'1.html\'>HTML5</a></li>");
document.writeln("			            <li><a  href=\'1.html\'>PHP</a></li>");
document.writeln("			            <li><a  href=\'1.html\'>MySQL</a></li>");
document.writeln("			            <li><a  href=\'1.html\'>JavaScript</a></li>");
document.writeln("		            </ul>");
document.writeln("	            </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("  </nav>");
document.writeln("  <script src=\'jquery-3.2.1.min.js\'></script>");
document.writeln("  <script src=\'popper.min.js\'></script>");
document.writeln("  <script src=\'bootstrap.min.js\'></script>");
document.writeln("</BODY>");
document.writeln("</HTML>");